use core::num::NonZero;

use bitflags::bitflags;

use crate::{
    Error,
    util::{Buf, BufMut, Decode, Encode},
};

/// Header of a method.
///
/// Don't forget that there're attributes followed!
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct MethodHeader {
    /// Access permission to and properties of this method.
    pub access_flags: MethodAccessFlags,
    /// Index of the name (`Utf8`) denoting this method in constant pool.
    pub name_index: NonZero<u16>,
    /// Index of the descriptor (`Utf8`) denoting this method in constant pool.
    pub descriptor_index: NonZero<u16>,
}

bitflags! {
    /// Denote access permissions to and properties of a method.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct MethodAccessFlags: u16 {
        /// Declared `public`; may be accessed from outside its package.
        const PUBLIC = 0x0001;
        /// Declared `private`;
        /// accessible only within the defining class and other classes belonging to the same nest.
        const PRIVATE = 0x0002;
        /// Declared `protected`; may be accessed within subclasses.
        const PROTECTED = 0x0004;
        /// Declared `static`.
        const STATIC = 0x0008;
        /// Declared `final`; never directly assigned to after object construction.
        const FINAL = 0x0010;
        /// Declared `synchronized`; invocation is wrapped by a monitor use.
        const SYNCHRONIZED = 0x0020;
        /// A bridge method, generated by the compiler.
        const BRIDGE = 0x0040;
        /// Declared with variable number of arguments.
        const VARARGS = 0x0080;
        /// Declared `native`; implemented in a language other than the Java programming language.
        const NATIVE = 0x0100;
        /// Declared abstract; no implementation is provided.
        const ABSTRACT = 0x0400;
        /// In a class file whose major version number is at least 46 and at most 60: Declared `strictfp`.
        const STRICT = 0x0800;
        /// Declared `synthetic`; not present in the source code.
        const SYNTHETIC = 0x1000;
    }
}

impl<'de> Decode<'de> for MethodHeader {
    fn decode<B: Buf<'de>>(mut buf: B) -> Result<Self, Error> {
        Ok(Self {
            access_flags: buf.read()?,
            name_index: buf.read()?,
            descriptor_index: buf.read()?,
        })
    }
}

impl Encode for MethodHeader {
    fn encode<B: BufMut>(&self, mut buf: B) -> Result<(), Error> {
        buf.write(self.access_flags)?;
        buf.write(self.name_index)?;
        buf.write(self.descriptor_index)?;
        Ok(())
    }
}

impl<'de> Decode<'de> for MethodAccessFlags {
    fn decode<B: Buf<'de>>(mut buf: B) -> Result<Self, Error> {
        let bits = buf.read()?;
        Ok(Self::from_bits_retain(bits))
    }
}

impl Encode for MethodAccessFlags {
    fn encode<B: BufMut>(&self, mut buf: B) -> Result<(), Error> {
        buf.write(self.bits())
    }
}
